### ISSUE TITLE
when I call validate function using instance of FormController, it's won't really validate for the fresh form

### ISSUE THREAD

**Issue by davidcheungo123** [micazi/form_controller#2]
When I call validate function using instance of FormController, it's won't really validate for the fresh form.

For example:
`  void initState() {
    _formController = FormController(controllers: {
      'q1': ('', false),
    });
    super.initState();
  }`

and I created a TextFormField for 'q1', the code is shown below:
`TextFormField(
                decoration: const InputDecoration(
                    label: Text("2. Study ID of the participant")),
                keyboardType: TextInputType.text,
                controller: _formController.controller('q2'),
                validator: FormControllerValidators.validate([
                  FormControllerValidators.isRequired(),
                  FormControllerValidators.minLength(1),
                ]),
                autovalidateMode: AutovalidateMode.onUserInteraction,
              ),`

When I don't do anything (a fresh form) and check if the field is validated by calling 
`_formController.validate()`
It returns true, do you have any idea to solve this issue? Thanks!

**Comment by micazi** [comment]
I can't reproduce the issue,
Would you mind updating the package and checking again?
If not, share the code you used.
Thank you!
